sudo: false
addons:
  apt:
    packages:
	- zlibc
    - libssl1.0.0
    - libbz2-dev
    - libxslt1-dev
    - libxml2-dev
    - python-virtualenv
    - python-dev
    - libfreetype6-dev
    - libpng12-dev
    - libffi-dev
    - libjpeg-dev
language: python
python:
  - "2.6"
  - "2.7"
  - "3.2"
  - "3.3"
  - "pypy"
  - "pypy3"
# command to install dependencies
install:
  - "make deploy"
# command to run tests
script: "make test-coverage-travis-ci" #nosetests
after_success:
  - "make test-coveralls"
